### ISSUE TITLE
Add an HTML preview tab.

### ISSUE THREAD

**Issue by Ayfri** [4ch1m/intellij-quick-jinja#4]
Hey, as a lot of frameworks use jinja2 templates for rendering HTML pages, it would be very useful to add an HTML preview tab.

**Comment by 4ch1m** [comment]
Cool idea. :+1: 
Should be possible to replace the result editor-view with a HTML-pane; or switch to it if needed.

**Comment by 4ch1m** [comment]
Added in version `1.2.0` (ac040a8bc9495184defa117225431effd4033e09) ; should soon be available in the marketplace.
Thanks again for the request.
