### ISSUE TITLE
Invalid syntax with Python 3.8

### ISSUE THREAD

**Issue by FrankyGee** [4ch1m/intellij-quick-jinja#5]
Hi. Perfect timing with this plugin - it's exactly what I'm looking for.

Sadly, I'm getting an error when running with Python 3.8
```
File "C:\<snip>\Temp\7130914192065531644.tmp", line 30
    with (open(r'C:\<snip>\Temp\83921477809611248.tmp') as template_file):
                                                        ^
SyntaxError: invalid syntax
```
The cause seems to be the outer brackets. It should be:
```
with open(r'C:\<snip>\Temp\87922477009611248.tmp') as template_file:
```
Note that I _assume_ this is an issue with Python 3.8 because that's the syntax error I get if I open the relevant .tmp file manually. I have tried to test this plugin with Python 3.11, but that's hard-locking my entire IDE (IntelliJ Ultimate) so I can't be sure exactly. I'll file a separate ticket for that issue if I get a chance to do more testing.

I realise 3.8 is getting pretty old, but (assuming no further issues) it's a minor change for backwards compatibility, if you're willing 🙏🏻

**Comment by 4ch1m** [comment]
Your assumption is correct.
"Parenthesized context managers" were introduced with Python 3.10.
However, that's not really needed here; so I removed the brackets (see: ac67ead4763b3aa1c471dc7ac10af86d2c392cc7).
The new plugin version (`1.5.1`) should be availabe for download soon.
