### ISSUE TITLE
utf-8

### ISSUE THREAD

**Issue by MorostCode** [4ch1m/intellij-quick-jinja#6]
When my parameters contain Chinese characters, it will prompt that the gbk encoding does not support this format. I hope to add utf-8 encoding support

**Comment by 4ch1m** [comment]
> When my parameters contain Chinese characters, it will prompt that the gbk encoding does not support this format.

What exactly do you mean with "parameters"?
Please be more precise and give examples (screenshots, etc.).

**Comment by MorostCode** [comment]
![image](https://github.com/user-attachments/assets/bff517db-78cb-4ea6-b39b-73f4be123f63)
Lines 15 18 22 24 contain Chinese characters, which will cause an error when I click the run button above "File". After removing the Chinese characters, the plugin rendering can run normally.

**Comment by 4ch1m** [comment]
All right. I see. :+1: 

Could you please upload a file here, that contains such characters; making it easier for me to implement/test a fix.

Thanks!

**Comment by 4ch1m** [comment]
I just tried to reproduce the issue with a GBK-file i found here: [GBK encoded Chinese text not auto-detected](https://bugs.documentfoundation.org/show_bug.cgi?id=92161)

I don't see any problems; it works fine in my case:

![image](https://github.com/user-attachments/assets/a32c0cc5-5b2a-4fa9-a26e-c45602333b2b)

**Comment by huan1936** [comment]
UTF8 needs to be declared in the plugin
```python
with (open(r'test.j2', encoding='utf8') as template_file):
    template = template_file.read()
```

**Comment by 4ch1m** [comment]
Please check [docs.python.org](https://docs.python.org/3/library/functions.html#open) ...

> if encoding is not specified the encoding used is platform-dependent: [locale.getencoding()](https://docs.python.org/3/library/locale.html#locale.getencoding) is called to get the current locale encoding.
