### ISSUE TITLE
is it possible to allow templates to be used?

### ISSUE THREAD

**Issue by HeadhunterXamd** [4ch1m/intellij-quick-jinja#7]
I have a main template where I have a default layout, and then the body is loaded based on the other files.
is it something you can add to the configuration?

**Comment by 4ch1m** [comment]
I guess a more elaborate example would help to understand you use-case.

**Comment by aleksykrolczyk** [comment]
I think whast @HeadhunterXamd meant is extending a template, say I have `base.html` and in other template I do
```jinja
{% extends "base.html" %}
  ...
{% endblock %}
```
In such scenario all is displayed is `no loader for this environment specified` - or is a matter of some configuration?

**Comment by 4ch1m** [comment]
I see.
For that we would have to implement (customizable) "loaders" for the Jinja2-environment which is being used to render the selected template (originating from a file, clipboard or editor-selection).
(In this/most cases probably a [FileSystemLoader](https://jinja.palletsprojects.com/en/stable/api/#jinja2.FileSystemLoader).)
It would also have to be accessible in the UI (possibly alongside the "Variables" tab?) for every run.

**Comment by 4ch1m** [comment]
Using outsourced templates via `extends`, `include` or `import` is now possible: 95a3f5976826534b7d636ed00f6f5b9db1c4d472

check: [Base-/Parent-Templates](https://github.com/4ch1m/intellij-quick-jinja?tab=readme-ov-file#base-parent-templates)
